; --------------------------------------------------------------
;  config.ini 2019-09-18
;  Gambio GmbH
;  http://www.gambio.de
;  Copyright (c) 2019 Gambio GmbH
;  Released under the GNU General Public License (Version 2)
;  [http://www.gnu.org/licenses/gpl-2.0.html]
;  --------------------------------------------------------------

[PHP_VERSION]
minPHPVersion = 7.2

[MySQL_VERSION]
minMySQLVersion = 5.5